name: CI + CD

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint: # Also checks formatting.
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup-env
        with:
          rust_cache_key: cargo
          rust_components: clippy, rustfmt

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
          key:
            ${{ runner.os }}-pre-commit-${{
            hashFiles('**/.pre-commit-config.yaml') }}

      - name: Run lint
        run: |
          just pre-commit
          just lint

  unit:
    name: Run unit test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup-env
        with:
          rust_cache_key: cargo

      - name: Run unit test
        run: just test

  build:
    name: Build release
    needs:
      - lint
      - unit
    strategy:
      fail-fast: false
      matrix:
        build:
          - linux
          - macos
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup-env
        with:
          rust_cache_key: cross
          rust_target: ${{ matrix.target }}

      - name: Build release
        run: |
          just get-cross
          just cross ${{ matrix.target }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: pls-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/pls

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup-env
        with:
          rust_cache_key: docs

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pls-x86_64-unknown-linux-musl
          path: /tmp/pls

      - name: Make binary accessible and executable
        run: |
          chmod +x /tmp/pls/pls
          echo "/tmp/pls" >> $GITHUB_PATH

      # This must be a separate step because `$PATH` changes are not reflected
      # immediately.
      - name: Ensure binary is accessible
        run: pls --version

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          python-version-file: examples/pyproject.toml
          cache-dependency-path: examples/pdm.lock

      - name: Enable Corepack
        run: corepack enable pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .nvmrc
          cache-dependency-path: docs/pnpm-lock.yaml
        env:
          COREPACK_INTEGRITY_KEYS: '{"npm":[{"expires":"2025-01-29T00:00:00.000Z","keyid":"SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1Olb3zMAFFxXKHiIkQO5cJ3Yhl5i6UPp+IhuteBJbuHcA5UogKo0EWtlWwW6KSaKoTNEYL7JlCQiVnkhBktUgg=="},{"expires":null,"keyid":"SHA256:DhQ8wR5APBvFHLF/+Tc+AYvPOdTpcIDqOhxsBHRwC7U","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEY6Ya7W++7aUPzvMTrezH6Ycx3c+HOKYCcNGybJZSCJq/fd7Qa8uuAKtdIkUQtQiEKERhAmE5lMMJhP8OkDOa2g=="}]}'

      - name: Install all dependencies
        run: just install

      - name: Generate examples
        working-directory: examples/
        run: just all

      - name: Build docs
        working-directory: docs/
        run: |
          pnpm build

      - name: Publish docs
        if: github.event_name == 'push'
        working-directory: docs/dist/
        run: |
          git init --initial-branch=gh-pages
          git config user.name "Dhruv Bhanushali"
          git config user.email "hi@dhruvkb.dev"
          git add .
          git commit --message "Build documentation"
          git remote add origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/pls-rs/pls-rs.github.io.git
          git push --force origin gh-pages
